# Main Hydra config
defaults:
  - data: data
  - model: model
  - train: train
  - federated: federated
  - logging: logging
  - mlflow: mlflow
  - eval: eval
  - _self_

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true
